excludes:
  # Reusable workflows don't support pinning version.
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml
