name: CD
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  ci:
    # actions/attest-build-provenance requires these permissions
    permissions:
      id-token: write
      attestations: write
    uses: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml@main
  cd:
    name: Release
    runs-on: ubuntu-24.04
    needs:
      - ci
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Output SHA
        uses: hudsonm62/short-sha@b5ee0a4109da599fea68b00dcfe5812100ad8d42 # v1.1.0
        id: short-sha
      - name: Download artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME="sha-${SHA}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "value=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "$TAG_NAME"
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{ steps.tag-name.outputs.value }}
          draft: false
          prerelease: true
          files: artifact/*.jar
