name: CD
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  ci:
    # actions/attest-build-provenance requires these permissions
    permissions:
      id-token: write
      attestations: write
    uses: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml@main
  cd:
    name: Release
    runs-on: ubuntu-22.04
    needs:
      - ci
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Output SHA
        uses: ./.github/actions/short-sha
        id: short-sha
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME="sha-${SHA}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "value=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "$TAG_NAME"
        env:
          SHA: ${{ steps.short-sha.outputs.SHA }}
      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ steps.tag-name.outputs.value }}
          draft: false
          prerelease: true
          files: artifact/*.jar
