name: CD
on:
  push:
    branches:
      - main
permissions: {}
jobs:
  ci:
    # actions/attest-build-provenance requires these permissions
    permissions:
      id-token: write
      attestations: write
    uses: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml@main
  cd:
    name: Release
    runs-on: ubuntu-24.04
    needs:
      - ci
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Output SHA
        uses: hudsonm62/short-sha@b5ee0a4109da599fea68b00dcfe5812100ad8d42 # v1.1.0
        id: short-sha
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME="sha-${SHA}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "value=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "$TAG_NAME"
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Create release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: ${{ steps.tag-name.outputs.value }}
          draft: false
          prerelease: true
          files: artifact/*.jar
