name: CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml@main
  cd:
    name: Deploy
    runs-on: ubuntu-22.04
    needs:
      - ci
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Output SHA
        uses: benjlevesque/short-sha@95aa1081125b46e95966cef05d7ef9b0e7e28557
        id: short-sha
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME="sha-${SHA}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
          echo "value=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "$TAG_NAME"
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Create release
        uses: softprops/action-gh-release@3362207ba10174a31da6ce64d9c9ea4bbee307f0
        with:
          tag_name: ${{ steps.tag-name.outputs.value }}
          draft: false
          prerelease: true
          files: artifact/*.jar
