name: CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: GiganticMinecraft/ObserverUtils/.github/workflows/ci.yaml@main
  cd:
    name: Deploy
    runs-on: ubuntu-22.04
    needs:
      - ci
    # softprops/action-gh-release requires this permisson
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Output SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create and push a tag
        id: tag-name
        run: |
          TAG_NAME="sha-${SHA}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "value=$TAG_NAME" >> $GITHUB_OUTPUT
          echo $TAG_NAME
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag-name.outputs.value }}
          draft: false
          prerelease: true
          files: artifact/*.jar
