name: CI and CD
on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "renovate.json"
      - ".github/workflows/**.yml"
      - "!.github/workflows/ci-and-cd.yml"

jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Upload a jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build/libs/
  cd:
    name: Release
    needs:
      - ci
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          # nyxがJava11以上を要求する
          java-version: '17'
          distribution: 'temurin'
      - name: Set git config as GHActions
        uses: Lucky3028/git-as-gha@v1.0.0
      - name: Release
        run: ./gradlew release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
