name: CI
on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "renovate.json"
      - ".github/workflows/**.yml"
      - "!.github/workflows/ci.yml"
jobs:
  ci:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: jar
      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test
      - name: Upload a jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build/libs/
