name: Lint GitHub Actions
on:
  push:
    paths:
      - .github/workflows/**
jobs:
  pinact:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/pinact-action@a60b07ee63e41654915780a3297ff9f5f6b6db63 # v0.1.0
        with:
          skip_push: false
