name: Lint GitHub Actions
on:
  push:
    paths:
      - .github/**
permissions: {}
jobs:
  pinact:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install pinact
        run: |
          wget "https://github.com/suzuki-shunsuke/pinact/releases/download/v${PINACT_VER}/pinact_linux_amd64.tar.gz"
          tar -xvf pinact_linux_amd64.tar.gz
          sudo mv pinact /usr/local/bin
        env:
          PINACT_VER: 0.2.1
      - name: Run pinact
        run: |
          pinact -c .github/pinact.yaml run
  ghalint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install ghalint
        run: |
          wget "https://github.com/suzuki-shunsuke/ghalint/releases/download/v${GHALINT_VER}/ghalint_${GHALINT_VER}_linux_amd64.tar.gz"
          tar -xvf "ghalint_${GHALINT_VER}_linux_amd64.tar.gz"
          sudo mv ghalint /usr/local/bin/
        env:
          GHALINT_VER: 0.2.12
      - name: Run ghalint
        run: |
          ghalint -c ./.github/ghalint.yaml run
      - name: Run ghalint for actions
        run: |
          ghalint run-action
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install actionlint
        run: |
          wget "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VER}/actionlint_${ACTIONLINT_VER}_linux_amd64.tar.gz"
          tar -xvf "actionlint_${ACTIONLINT_VER}_linux_amd64.tar.gz"
          sudo mv actionlint /usr/local/bin/
        env:
          ACTIONLINT_VER: 1.7.1
      - name: Run actionlint
        run: |
          actionlint
