name: Lint GitHub Actions
on:
  push:
    paths:
      - .github/workflows/**
jobs:
  pinact:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pinact
        run: |
          wget "https://github.com/suzuki-shunsuke/pinact/releases/download/v${PINACT_VER}/pinact_linux_arm64.tar.gz"
          tar -xvf pinact_linux_arm64.tar.gz
          sudo mv pinact /usr/local/bin
        env:
          PINACT_VER: 0.2.1
      - uses: suzuki-shunsuke/pinact-action@a60b07ee63e41654915780a3297ff9f5f6b6db63 # v0.1.0
        with:
          skip_push: false
