name: Lint GitHub Actions
on:
  push:
    paths:
      - .github/**
permissions: {}
jobs:
  pinact:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install pinact
        run: |
          wget "https://github.com/suzuki-shunsuke/pinact/releases/download/v${PINACT_VER}/pinact_linux_amd64.tar.gz"
          tar -xvf pinact_linux_amd64.tar.gz
          sudo mv pinact /usr/local/bin
        env:
          PINACT_VER: 0.2.1
      - name: Run pinact
        run: |
          pinact -c .github/pinact.yaml run
  ghalint:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install ghalint
        run: |
          wget "https://github.com/suzuki-shunsuke/ghalint/releases/download/v${GHALINT_VER}/ghalint_${GHALINT_VER}_linux_amd64.tar.gz"
          tar -xvf "ghalint_${GHALINT_VER}_linux_amd64.tar.gz"
          sudo mv ghalint /usr/local/bin/
        env:
          GHALINT_VER: 0.2.12
      - name: Run ghalint
        run: |
          ghalint -c ./.github/ghalint.yaml run
      - name: Run ghalint for actions
        run: |
          ghalint run-action
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run actionlint
        uses: reviewdog/action-actionlint@4f8f9963ca57a41e5fd5b538dd79dbfbd3e0b38a # v1.54.0
        with:
          reporter: github-pr-review
          fail_on_error: true

